import type { WorkflowTemplate } from './types';

const retryPolicy = { maxAttempts: 1, delayMs: 250 };
export const templateCatalog: readonly WorkflowTemplate[] = [
  { id: 'summarize-page', schemaVersion: 1, name: 'Summarize current page', description: 'Read the main content and create a concise summary.', category: 'page', tags: ['summary', 'article'], triggerDomains: [], risk: 'read', executionMode: 'current_tab', variables: [], version: { steps: [{ id: 'read', type: 'action', label: 'Read main content', enabled: true, timeoutMs: 15000, retryPolicy, onFailure: 'repair', toolName: 'browser_get_summary', input: '1200', risk: 'read' }], finalAssertions: [] } },
  { id: 'compare-tabs', schemaVersion: 1, name: 'Compare selected tabs', description: 'Compare the important facts across selected tabs.', category: 'research', tags: ['compare', 'research', 'tabs'], triggerDomains: [], risk: 'read', executionMode: 'current_tab', variables: [{ key: 'tabs', label: 'Tabs', type: 'tabs', required: true }], version: { steps: [{ id: 'read', type: 'action', label: 'Read current page', enabled: true, timeoutMs: 15000, retryPolicy, onFailure: 'repair', toolName: 'browser_read_text', input: '', risk: 'read' }], finalAssertions: [] } },
  { id: 'extract-custom-fields', schemaVersion: 1, name: 'Extract custom fields', description: 'Extract fields from the current page into structured rows.', category: 'data', tags: ['extract', 'table', 'json'], triggerDomains: [], risk: 'read', executionMode: 'current_tab', variables: [{ key: 'fields', label: 'Fields', type: 'fields', required: true }], version: { steps: [{ id: 'extract', type: 'ai_step', label: 'Extract structured data', enabled: true, timeoutMs: 30000, retryPolicy, onFailure: 'stop', toolName: 'browser_extract_structured', input: '{{fields}}', risk: 'read' }], finalAssertions: [] } },
  { id: 'export-page-table', schemaVersion: 1, name: 'Export page table', description: 'Extract a visible table and download it as CSV.', category: 'data', tags: ['table', 'csv', 'export'], triggerDomains: [], risk: 'write', executionMode: 'current_tab', variables: [], version: { steps: [{ id: 'extract', type: 'action', label: 'Read page table', enabled: true, timeoutMs: 15000, retryPolicy, onFailure: 'stop', toolName: 'browser_extract_structured', input: '[]', risk: 'read' }, { id: 'export', type: 'action', label: 'Download CSV', enabled: true, timeoutMs: 15000, retryPolicy, onFailure: 'stop', toolName: 'browser_export_data', input: 'csv', risk: 'write' }], finalAssertions: [] } },
];
