import React, { useEffect, useState } from 'react';
import type { OfficeReport } from '../../../office/types';
import { reportCsv, safePathPart } from '../../../office/report';
export function OfficeReportView({ report: initial, runId, stepRunId }: { report: OfficeReport; runId: string; stepRunId: string }) {
  const [report, setReport] = useState(initial);
  const [selected, setSelected] = useState<string[]>([]);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { setReport(initial); }, [initial]);
  const archive = async (download = false) => {
    setBusy(true); setError('');
    try {
      const response = await chrome.runtime.sendMessage({ action: download ? 'officeArchiveDownload' : 'officeArchiveRefresh', runId, stepRunId, fileIds: selected });
      if (!response.success) throw new Error(response.error);
      setReport(response.data); if (download) setSelected([]);
    } catch (cause) { setError(String(cause instanceof Error ? cause.message : cause)); } finally { setBusy(false); }
  };
  const exportCsv = async () => {
    const url = URL.createObjectURL(new Blob([reportCsv(report)], { type: 'text/csv;charset=utf-8' }));
    try { await chrome.downloads.download({ url, filename: `${safePathPart(report.config.name)}.csv`, saveAs: true }); }
    catch (cause) { setError(String(cause)); }
    finally { setTimeout(() => URL.revokeObjectURL(url), 60000); }
  };
  return <section aria-label="Office report" className="space-y-3 rounded-lg border border-stone-200 p-3">
    <div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">{report.config.name}</h3><span className={`text-xs ${report.complete ? 'text-emerald-700' : 'text-amber-700'}`}>{report.complete ? 'Complete' : 'Partial results'}</span></div>
    <p className="text-xs text-stone-600">{report.pages} pages · {report.scanned} rows inspected · {report.rows.length} matched</p>
    {report.warnings.map(warning => <p key={warning} className="text-xs text-amber-800">{warning}</p>)}
    {report.comparison && <p className="rounded-md bg-stone-50 p-2 text-xs leading-5">Compared with {new Date(report.comparison.previousAt).toLocaleString()}: {report.comparison.added.length} new, {report.comparison.changed.length} changed, {report.comparison.unchanged.length} unchanged, {report.comparison.noLongerMatched.length} no longer match. Records that no longer match are not necessarily resolved.</p>}
    <button onClick={exportCsv} className="text-xs font-semibold text-[#315a78]">Export matching rows as CSV</button>
    <div className="max-h-80 overflow-auto"><table className="w-full text-left text-[11px]"><thead className="bg-stone-100"><tr>{report.config.headers.map((header, index) => <th key={index} className="p-2 whitespace-nowrap">{header}</th>)}<th className="p-2">Source</th></tr></thead><tbody>{report.rows.map(row => <tr key={row.key} className="border-b border-stone-100">{row.cells.map((cell, index) => <td key={index} className="p-2 min-w-24 max-w-48 break-words">{cell}</td>)}<td className="p-2"><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="text-[#315a78]">Open</a></td></tr>)}</tbody></table>{!report.rows.length && <p className="p-2 text-xs text-stone-500">No matching rows in the pages read.</p>}</div>
    {!!report.comparison?.noLongerMatched.length && <details className="text-xs"><summary>No longer matching records</summary>{report.comparison.noLongerMatched.map(row => <p key={row.key} className="mt-2 break-words">{row.cells.join(' · ')}</p>)}</details>}
    {report.config.mode === 'archive' && <div className="space-y-2 border-t border-stone-200 pt-3"><div className="flex items-center justify-between"><h4 className="text-xs font-semibold">Files ({report.files.length})</h4><button disabled={busy} onClick={() => archive()} className="text-xs text-[#315a78]">Refresh status</button></div><p className="text-[11px] text-stone-500">Downloads / BrowserOnly / {safePathPart(report.config.name)} / {new Date(report.startedAt).toISOString().slice(0, 10)}</p>{!report.files.length && <p className="text-xs text-stone-500">No supported file links found in matching rows. Downloads generated by site buttons need a custom workflow.</p>}{report.files.map(file => <label key={file.id} className="flex items-start gap-2 border-b border-stone-100 py-2 text-xs"><input type="checkbox" disabled={busy || !['ready', 'failed'].includes(file.status)} checked={selected.includes(file.id)} onChange={e => setSelected(current => e.target.checked ? [...current, file.id] : current.filter(id => id !== file.id))} /><span className="min-w-0 flex-1 break-words"><a href={file.url} target="_blank" rel="noreferrer" className="text-[#315a78]">{file.name}</a><span className="mt-1 block text-stone-500">{file.status}{file.error ? `: ${file.error}` : ''}</span></span></label>)}<button disabled={busy || !selected.length} onClick={() => archive(true)} className="rounded-md bg-[#315a78] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? 'Updating…' : `Download selected (${selected.length})`}</button></div>}
    {error && <p role="alert" className="text-xs text-red-700">{error}</p>}
  </section>;
}
