import React, { useEffect, useState } from 'react';
import type { Monitor, MonitorDiff, MonitorRun, MonitorScreenshot, MonitorSnapshot } from '../../../monitoring';

const displayValue = (value: MonitorSnapshot['normalizedValue'] | MonitorDiff['currentValue'] | undefined) => value?.type === 'text' ? value.text
  : value?.type === 'price' ? `${value.currency ? `${value.currency} ` : ''}${value.amount}`
  : value?.type === 'stock' ? value.state.replaceAll('_', ' ') : 'No successful baseline';

export function MonitorDetailView({ monitorId, onBack }: { monitorId: string; onBack: () => void }) {
  const [data, setData] = useState<{ monitor: Monitor; runs: MonitorRun[]; snapshots: MonitorSnapshot[]; diffs: MonitorDiff[]; screenshots: MonitorScreenshot[] }>();
  const load = () => chrome.runtime.sendMessage({ action: 'monitorGet', monitorId }).then(response => { if (response.success) setData(response.data); });
  useEffect(() => { load(); const listener = (message: any) => { if (message.action === 'monitorRunUpdated' && message.monitorId === monitorId) load(); }; chrome.runtime.onMessage.addListener(listener); return () => chrome.runtime.onMessage.removeListener(listener); }, [monitorId]);
  if (!data) return <p className="text-xs text-stone-500">Loading…</p>;
  const current = data.snapshots[0];
  return <div className="space-y-4"><div className="flex items-center justify-between"><button onClick={onBack} className="text-sm text-stone-500">← Monitors</button><button onClick={() => chrome.runtime.sendMessage({ action: data.monitor.status === 'active' ? 'monitorPause' : 'monitorResume', monitorId }).then(load)} className="text-xs font-semibold text-[#315a78]">{data.monitor.status === 'active' ? 'Pause' : 'Resume'}</button></div>
    <div><h2 className="text-base font-semibold text-stone-900">{data.monitor.name}</h2><p className="mt-1 truncate text-xs text-stone-500">{data.monitor.url}</p></div>
    <div className="rounded-xl border border-stone-200 bg-stone-50 p-3"><p className="text-[11px] uppercase text-stone-500">Current value</p><p className="mt-1 break-words text-sm font-semibold">{displayValue(current?.normalizedValue)}</p><p className="mt-2 text-[11px] text-stone-500">{data.monitor.lastCheckedAt ? `Last checked ${new Date(data.monitor.lastCheckedAt).toLocaleString()}` : 'Not checked'}</p></div>
    <div><h3 className="mb-2 text-xs font-semibold uppercase text-stone-500">History</h3><div className="space-y-2">{data.runs.map(run => { const diff = data.diffs.find(item => item.id === run.diffId); const snapshot = data.snapshots.find(item => item.id === run.snapshotId); const screenshot = data.screenshots.find(item => item.id === snapshot?.screenshotId); return <div key={run.id} className="rounded-lg border border-stone-200 p-3 text-xs"><div className="flex justify-between"><span className="font-medium">{run.source === 'creation' ? 'Baseline' : run.status}</span><span className="text-stone-400">{new Date(run.startedAt).toLocaleString()}</span></div>{run.status === 'failed' && <p className="mt-1 text-red-600">{run.errorCode}: {run.errorMessage}</p>}{diff?.changed && <><p className="mt-1 break-words text-stone-600">{displayValue(diff.previousValue)} → {displayValue(diff.currentValue)}{typeof diff.numericDelta === 'number' ? ` (${diff.numericDelta > 0 ? '+' : ''}${diff.numericDelta}${typeof diff.percentDelta === 'number' ? `, ${diff.percentDelta.toFixed(1)}%` : ''})` : ''}</p>{diff.addedText?.length ? <p className="mt-1 text-green-700">Added: {diff.addedText.join(' ')}</p> : null}{diff.removedText?.length ? <p className="mt-1 text-red-700">Removed: {diff.removedText.join(' ')}</p> : null}</>}{screenshot && typeof screenshot.data === 'string' && <img src={screenshot.data} alt={`Page evidence from ${new Date(screenshot.createdAt).toLocaleString()}`} className="mt-2 max-h-48 w-full rounded border border-stone-200 object-contain" />}</div>; })}{!data.runs.length && <p className="text-xs text-stone-500">No runs yet.</p>}</div></div>
  </div>;
}
