import React, { useEffect, useMemo, useState } from 'react';
import { TemplateCatalog, instantiateTemplate, markTemplateUsed, readTemplateUsage, type WorkflowTemplate } from '../../../templates';
import { WorkflowStore } from '../../../workflows';

const catalog = new TemplateCatalog();
const categories = ['all', 'page', 'research', 'data', 'writing'] as const;
export function TemplateLibraryView({ onWorkflowCreated, onRun }: { onWorkflowCreated: (id: string) => void; onRun: (template: WorkflowTemplate) => void }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<string>('page'); const [url, setUrl] = useState(''); const [usage, setUsage] = useState({}); const [selected, setSelected] = useState<WorkflowTemplate>();
  useEffect(() => { chrome.tabs.query({ active: true, lastFocusedWindow: true }).then(tabs => setUrl(tabs[0]?.url ?? '')); readTemplateUsage().then(setUsage); }, []);
  const templates = useMemo(() => catalog.search({ query, category, url, usage }), [query, category, url, usage]);
  const customize = async (template: WorkflowTemplate) => { const candidate = instantiateTemplate(template); const store = WorkflowStore.getInstance(); await store.saveVersion(candidate.version); await store.saveWorkflow(candidate.workflow); await markTemplateUsed(template.id); onWorkflowCreated(candidate.workflow.id); };
  if (selected) return <TemplateDetail template={selected} onBack={() => setSelected(undefined)} onCustomize={() => customize(selected)} onRun={() => { markTemplateUsed(selected.id); onRun(selected); }} />;
  return <div className="space-y-3"><input aria-label="Search templates" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search templates..." className="w-full rounded-md border border-stone-300 px-3 py-2 text-sm outline-none focus:border-[#315a78]" /><div className="flex gap-1 overflow-x-auto pb-1">{categories.map(item => <button key={item} type="button" onClick={() => setCategory(item)} aria-pressed={category === item} className={`shrink-0 rounded-full px-2.5 py-1 text-xs ${category === item ? 'bg-[#315a78] text-white' : 'bg-stone-100 text-stone-600'}`}>{item === 'page' ? 'For this page' : item[0].toUpperCase() + item.slice(1)}</button>)}</div><div className="divide-y divide-stone-200">{templates.map(template => <div key={template.id} className="flex items-start gap-3 py-3"><button type="button" onClick={() => setSelected(template)} className="min-w-0 flex-1 text-left"><div className="text-sm font-semibold text-stone-900">{template.name}</div><div className="mt-0.5 text-xs leading-5 text-stone-500">{template.description}</div><div className="mt-1 text-[11px] text-stone-400">{template.executionMode === 'new_tab' ? 'Opens a new tab' : 'Uses current page'}</div></button><button type="button" onClick={() => setSelected(template)} className="rounded-md bg-[#315a78] px-2.5 py-1.5 text-xs font-semibold text-white">Use</button></div>)}{templates.length === 0 && <div className="py-8 text-center text-xs text-stone-500">No matching templates. <button type="button" className="font-semibold text-[#315a78]" onClick={() => { setQuery(''); setCategory('all'); }}>Show all</button></div>}</div></div>;
}

function TemplateDetail({ template, onBack, onCustomize, onRun }: { template: WorkflowTemplate; onBack: () => void; onCustomize: () => void; onRun: () => void }) {
  return <div className="space-y-4"><button type="button" onClick={onBack} className="text-xs text-stone-500">← Templates</button><div><h2 className="text-base font-semibold text-stone-900">{template.name}</h2><p className="mt-1 text-xs leading-5 text-stone-600">{template.description}</p></div><section><h3 className="text-[11px] font-semibold uppercase tracking-wide text-stone-500">What it will do</h3><ol className="mt-2 space-y-2">{template.version.steps.map((step, index) => <li key={step.id} className="flex gap-2 text-xs text-stone-700"><span className="text-stone-400">{index + 1}</span><span>{step.label}</span></li>)}</ol></section><div className={`rounded-md border px-3 py-2 text-xs ${template.risk === 'read' ? 'border-stone-200 bg-stone-50 text-stone-600' : 'border-amber-200 bg-amber-50 text-amber-800'}`}>{template.risk === 'read' ? 'Reads page content. Does not submit forms.' : `Contains ${template.risk} actions. Approval may be required.`}</div><div className="flex justify-end gap-2"><button type="button" onClick={onCustomize} className="rounded-md border border-stone-300 px-3 py-2 text-xs font-semibold">Customize</button><button type="button" onClick={onRun} className="rounded-md bg-[#315a78] px-3 py-2 text-xs font-semibold text-white">Run now</button></div></div>;
}
